repos:
  - repo: local
    hooks:
      - id: pre-push
        name: pre-push
        stages: [push]
        language: system
        entry: bash -c "pushd src && source ../hooks/pre-push; popd"
        require_serial: true
