[tool.ruff]
indent-width = 2

[tool.ruff.lint]
select = ["D", "E", "F"]
ignore = ["D100", "E501"] # Ignore "Missing docstring in public module" and "Line to long"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["D"] # Don't require docstrings in unit tests

[tool.pytest.ini_options]
pythonpath = [
  "./src"
]

[tool.coverage.run]
branch = true
omit = [
  "test_*.py",
  "/**/test/helpers.py",
  "/**/test_helpers/helpers.py"
]

[tool.coverage.report]
include_namespace_packages = true
show_missing = true
fail_under = 90
