[tool.ruff]
indent-width = 2

[tool.ruff.lint]
select = ["D"] # Require docstrings
ignore = ["D100"] # Ignore "Missing docstring in public module"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["D"] # Don't require docstrings in unit tests

[tool.pytest.ini_options]
pythonpath = [
  "./src"
]

[tool.coverage.run]
branch = true
omit = [
  "test_*.py",
  "/**/test/helpers.py"
]

[tool.coverage.report]
include_namespace_packages = true
show_missing = true
fail_under = 95
