#!/bin/bash

set -e pipefail

FILE_DIR="$(dirname $0)"

pushd "$FILE_DIR"/../src

echo "--- Running type check ---"
mypy --strict --explicit-package-bases .

echo "--- Running lint check ---"
ruff check

echo "--- Running format check ---"
ruff format --diff

popd

echo "--- Running unit tests ---"
pytest --cov="$FILE_DIR"/../src --cov-config="$FILE_DIR"/../pyproject.toml
