#!/bin/bash

set -e pipefail

FILE_PATH=$(realpath "$0")
FILE_DIR=$(dirname "$FILE_PATH")

echo "File dir: $FILE_DIR"

pushd "$FILE_DIR"/../src

echo "--- Running type check ---"
mypy --strict --explicit-package-bases .

echo "--- Running lint check ---"
ruff check

echo "--- Running format check ---"
ruff format --diff

echo "File dir: $FILE_DIR"

popd

echo "--- Running unit tests ---"
pytest --cov="$FILE_DIR"/../src --cov-config="$FILE_DIR"/../pyproject.toml --rootdir="$FILE_DIR"/../src
