#!/bin/bash

set -e pipefail

pushd ./src

echo "--- Running type check ---"
mypy --strict --explicit-package-bases .

echo "--- Running lint check ---"
ruff check

echo "--- Running format check ---"
ruff format --diff

popd

echo "--- Running unit tests ---"
pytest --cov=./src -rootdir=./src
